repos:
  - repo: https://github.com/awslabs/git-secrets
    rev: b9e96b3212fa06aea65964ff0d5cda84ce935f38
    hooks:
      - id: git-secrets
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: ^discovery-provider/alembic/
        stages: [push]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: ^discovery-provider/alembic/
        stages: [push]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        exclude: ^discovery-provider/alembic/
        additional_dependencies:
          - 'sqlalchemy-stubs'
          - 'types-python-dateutil'
          - 'types-redis'
          - 'types-requests'
          - 'types-pytz'
        stages: [push]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
